# Generated by Django 6.0.3 on 2026-03-25 14:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydroBasin',
            fields=[
                ('hybas_id', models.PositiveIntegerField(help_text='Unique basin identifier.', primary_key=True, serialize=False)),
                ('next_down', models.BigIntegerField(blank=True, help_text='Hybas_id of the next downstream polygon.', null=True)),
                ('next_sink', models.BigIntegerField(blank=True, help_text='Hybas_id of the next downstream sink.', null=True)),
                ('main_bas', models.BigIntegerField(blank=True, help_text='Hybas_id of the most downstream sink, i.e. the outlet of the main river basin.', null=True)),
                ('dist_sink', models.FloatField(blank=True, help_text='Distance from polygon outlet to the next downstream sink along the river network, in kilometers.', null=True)),
                ('dist_main', models.FloatField(blank=True, help_text='Distance from polygon outlet to the most downstream sink, i.e. the outlet of the main river basin, in km.', null=True)),
                ('sub_area', models.FloatField(blank=True, help_text='Area of the individual polygon (i.e. sub-basin), in square kilometers.', null=True)),
                ('up_area', models.FloatField(blank=True, help_text='Total upstream area, in square kilometers, calculated from the headwaters to the polygon location.', null=True)),
                ('pfaf_id', models.IntegerField(blank=True, help_text='The Pfafstetter code.', null=True)),
                ('endo', models.IntegerField(blank=True, help_text='Indicator for endorheic (inland) basins without surface flow connection to the ocean.', null=True)),
                ('coast', models.IntegerField(blank=True, help_text='Indicator for lumped coastal basins.', null=True)),
                ('order', models.IntegerField(blank=True, help_text='Indicator of river order (classical ordering system).', null=True)),
                ('sort', models.BigIntegerField(blank=True, help_text='Indicator showing the record number (sequence) in which the original polygons are stored in the shapefile.', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Geometry of the sub-basin polygon', null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydroLake',
            fields=[
                ('hylak_id', models.PositiveIntegerField(help_text='Unique lake identifier.', primary_key=True, serialize=False)),
                ('lake_name', models.CharField(blank=True, help_text='Name of lake or reservoir.', max_length=40, null=True)),
                ('country', models.CharField(blank=True, help_text='Country that the lake (or reservoir) is located in.', max_length=35, null=True)),
                ('continent', models.CharField(blank=True, help_text='Continent that the lake (or reservoir) is located in.', max_length=15, null=True)),
                ('poly_src', models.CharField(blank=True, help_text='Source of original lake polygon.', max_length=10, null=True)),
                ('lake_type', models.IntegerField(blank=True, help_text='Indicator for lake type: 1=Lake, 2=Reservoir, 3=Lake control.', null=True)),
                ('grand_id', models.IntegerField(blank=True, help_text='ID of the corresponding reservoir in the GRanD database.', null=True)),
                ('lake_area', models.FloatField(blank=True, help_text='Lake surface area (i.e. polygon area), in square kilometers.', null=True)),
                ('shore_len', models.FloatField(blank=True, help_text='Length of shoreline (i.e. polygon outline), in kilometers.', null=True)),
                ('shore_dev', models.FloatField(blank=True, help_text='Shoreline development, measured as the ratio between shoreline length and circumference of a circle with the same area.', null=True)),
                ('vol_total', models.FloatField(blank=True, help_text='Total lake or reservoir volume, in million cubic meters.', null=True)),
                ('vol_res', models.FloatField(blank=True, help_text='Reported reservoir volume, or storage volume of added lake regulation, in million cubic meters.', null=True)),
                ('vol_src', models.IntegerField(blank=True, help_text='1: reported total lake volume, 2: reported total reservoir volume, 3: estimated total lake volume.', null=True)),
                ('depth_avg', models.FloatField(blank=True, help_text='Average lake depth, in meters.', null=True)),
                ('dis_avg', models.FloatField(blank=True, help_text='Average long-term discharge flowing through the lake, in cubic meters per second.', null=True)),
                ('res_time', models.FloatField(blank=True, help_text='Average residence time of the lake water, in days.', null=True)),
                ('elevation', models.IntegerField(blank=True, help_text='Elevation of lake surface, in meters above sea level.', null=True)),
                ('slope_100', models.FloatField(blank=True, help_text='Average slope within a 100 meter buffer around the lake polygon, in degrees.', null=True)),
                ('wshd_area', models.FloatField(blank=True, help_text='Area of the watershed associated with the lake, in square kilometers.', null=True)),
                ('pour_long', models.FloatField(blank=True, help_text='Longitude of the lake pour point, in decimal degrees.', null=True)),
                ('pour_lat', models.FloatField(blank=True, help_text='Latitude of the lake pour point, in decimal degrees.', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geometry of the lake pour point', null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydroRiver',
            fields=[
                ('hyriv_id', models.PositiveIntegerField(help_text='Unique identifier for each river reach.', primary_key=True, serialize=False)),
                ('next_down', models.IntegerField(blank=True, help_text='HYRIV_ID of the next downstream line segment.', null=True)),
                ('main_riv', models.IntegerField(blank=True, help_text='HYRIV_ID of the most downstream reach of the connected river basin.', null=True)),
                ('length_km', models.FloatField(blank=True, help_text='Length of the river reach segment, in kilometers.', null=True)),
                ('dist_dn_km', models.FloatField(blank=True, help_text='Distance from the reach outlet to the final downstream location along the river network, in km.', null=True)),
                ('dist_up_km', models.FloatField(blank=True, help_text='Distance from the reach outlet to the most upstream location along the river network, in km.', null=True)),
                ('catch_skm', models.FloatField(blank=True, help_text='Area of the catchment that contributes directly to the individual reach, in square kilometers.', null=True)),
                ('upland_skm', models.FloatField(blank=True, help_text='Total upstream area, in square kilometers, calculated from the headwaters to the pour point.', null=True)),
                ('endorheic', models.IntegerField(blank=True, help_text='Indicator for endorheic (inland) basins without surface flow connection to the ocean.', null=True)),
                ('dis_av_cms', models.FloatField(blank=True, help_text='Average long-term discharge estimate for river reach, in cubic meters per second.', null=True)),
                ('ord_stra', models.IntegerField(blank=True, help_text='Indicator of river order following the Strahler ordering system.', null=True)),
                ('ord_clas', models.IntegerField(blank=True, help_text='Indicator of river order following the classical ordering system.', null=True)),
                ('ord_flow', models.IntegerField(blank=True, help_text='Indicator of river order using river flow to distinguish logarithmic size classes.', null=True)),
                ('hybas_l12', models.BigIntegerField(blank=True, help_text='HYBAS_ID of the corresponding HydroBASINS sub-basin in which the river reach resides.', null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Geometry of the river reach', null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HydroWaste',
            fields=[
                ('waste_id', models.BigIntegerField(help_text='ID of WWTP in HydroWASTE', primary_key=True, serialize=False)),
                ('source', models.IntegerField(blank=True, help_text='National/regional dataset: 1 = Europe; 2 = United States; 3 = Brazil; 4 = Mexico; 5 = China; 6 = Canada; 7 = Australia; 8 = South Africa; 9 = India; 10 = New Zealand; 11 = Peru; 12 = Remaining Countries', null=True)),
                ('org_id', models.CharField(blank=True, help_text='ID from national/regional dataset (see reference paper for more information)', max_length=255, null=True)),
                ('wwtp_name', models.CharField(blank=True, help_text='Name of the WWTP from national/regional dataset (empty if not reported)', max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='Country in which WWTP is located', max_length=255, null=True)),
                ('cntry_iso', models.CharField(blank=True, help_text='Country ISO', max_length=255, null=True)),
                ('lat_wwtp', models.FloatField(blank=True, help_text='Latitude of reported WWTP location', null=True)),
                ('lon_wwtp', models.FloatField(blank=True, help_text='Longitude of reported WWTP location', null=True)),
                ('qual_loc', models.IntegerField(blank=True, help_text='Quality indicator related to reported WWTP location (see SI of reference paper for more information): 1 = high (tests indicated >80% of reported WWTP locations in country/region to be accurate); 2 = medium (tests indicated between 50% and 80% of reported WWTP locations in country/region to be accurate); 3 = low (tests indicated <50% of reported WWTP locations in country/region to be accurate); 4 = Quality of WWTP locations in country/region not analysed', null=True)),
                ('lat_out', models.FloatField(blank=True, help_text='Latitude of the estimated outfall location (see reference paper for more information)', null=True)),
                ('lon_out', models.FloatField(blank=True, help_text='Longitude of the estimated outfall location (see reference paper for more information)', null=True)),
                ('status', models.CharField(blank=True, help_text='Status of the WWTP from national/regional dataset: Closed, Construction Completed, Decommissioned, Non-Operational, Operational, Projected, Proposed, Under Construction, Not Reported (assumed operational)', max_length=255, null=True)),
                ('pop_served', models.FloatField(blank=True, help_text='Population served by the WWTP', null=True)),
                ('qual_pop', models.IntegerField(blank=True, help_text="Quality indicator related to the attribute 'population served' (see reference paper for more information): 1 = Reported as ‘population served’ by national/regional dataset; 2 = Reported as ‘population equivalent’ by national/regional dataset; 3 = Estimated (with wastewater discharge available); 4 = Estimated (without wastewater discharge available)", null=True)),
                ('waste_dis', models.FloatField(blank=True, help_text='Treated wastewater discharged by the WWTP in m3 d-1', null=True)),
                ('qual_waste', models.IntegerField(blank=True, help_text="Quality indicator related to the attribute 'Treated wastewater discharged' (see reference paper for more information): 1 = Reported as ‘treated’ by national/regional dataset; 2 = Reported as ‘design capacity’ by national/regional dataset; 3 = Reported but type not identified; 4 = Estimated", null=True)),
                ('level', models.CharField(blank=True, help_text='Level of treatment of the WWTP: Primary, Secondary, Advanced', max_length=255, null=True)),
                ('qual_level', models.IntegerField(blank=True, help_text="Quality indicator related to the attribute 'level of treatment' (see reference paper for more information): 1 = Reported by national/regional dataset; 2 = Estimated", null=True)),
                ('df', models.FloatField(blank=True, help_text='Estimated dilution factor (empty if estimated outfall location is the ocean or large lake; see reference paper for more information)', null=True)),
                ('hyriv_id', models.BigIntegerField(blank=True, help_text='ID of associated river reach in RiverATLAS at estimated outfall location (link to HydroATLAS database; empty if estimated outfall location is the ocean or an endorheic sink)', null=True)),
                ('river_dis', models.FloatField(blank=True, help_text='Estimated river discharge at the WWTP outfall location in m3 s-1 (derived from HydroATLAS database; empty if estimated outfall location is the ocean)', null=True)),
                ('coast_10km', models.IntegerField(blank=True, help_text='1 = Estimated outfall location within 10 km of the ocean or a large lake (surface area larger than 500 km2); 0 = Estimated outfall location further than 10 km of the ocean or a large lake (surface area larger than 500 km2)', null=True)),
                ('coast_50km', models.IntegerField(blank=True, help_text='1 = Estimated outfall location within 50 km of the ocean or a large lake (surface area larger than 500 km2); 0 = Estimated outfall location further than 50 km of the ocean or a large lake (surface area larger than 500 km2)', null=True)),
                ('design_cap', models.FloatField(blank=True, help_text='Design capacity of WWTP as reported in national/regional dataset (empty if not reported)', null=True)),
                ('qual_cap', models.IntegerField(blank=True, help_text="Quality indicator related to the attribute 'design capacity': 1 = Reported as design capacity in m3 d-1; 2 = Reported as design capacity in 'population equivalent'; 3 = Not reported", null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geometry of the WWTP', null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
